spring:
  profiles:
    active:
      - local_dev
  datasource:
    url: jdbc:mysql://localhost:3306/template?allowPublicKeyRetrieval=TRUE&useSSL=FALSE&createDatabaseIfNotExist=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1a2b3c4d
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  messages:
    basename: message
    encoding: UTF-8
    fallback-to-system-locale=: true
logging:
  level:
    org:
      springframework: info
application:
  core:
    env: "build"
