spring:
  datasource:
    url: jdbc:mysql://localhost:3306/template?allowPublicKeyRetrieval=TRUE&useSSL=FALSE&createDatabaseIfNotExist=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1a2b3c4d
application:
  core:
    env: "dev"