version: "3.1"
# https://docs.docker.com/compose/compose-file/

services:

  db:
    image: mysql:8.0.26
    # Set max_allowed_packet to 512M for provisioning
    command: --max-allowed-packet=512M --performance-schema=FALSE --transaction-isolation=READ-COMMITTED --init-connect='SET collation_connection=utf8mb4_unicode_ci' --init-connect='SET NAMES utf8mb4;' --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower-case-table-names=2 --max-connections=500
    container_name: template_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1a2b3c4d
    ports:
      - "3306:3306"
    networks:
      - template-network
      ## change network name to project name?
      ## volumes:
      ## - ./mysql/config:/etc/mysql/conf.d
      ## - soc-dev-data:/var/lib/mysql

  core-be:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - template-network

volumes:
  core-dev-data:

networks:
  template-network:
    name: template-network